### ISSUE TITLE
migrate to pnpm and monorepo

### ISSUE THREAD

**Issue by reslear** [niklasfjeldberg/vue-strapi-blocks-renderer#8]
As part of #6, propose migrate to `pnpm` and `monorepo` 
@niklasfjeldberg what do you think? I could do that

**Comment by niklasfjeldberg** [comment]
Sure, go ahead!

**Comment by niklasfjeldberg** [comment]
I already moved to `pnpm`, and as you moved on from this rep I will close this issue.

**Comment by reslear** [comment]
but it was meant to separate playground and library with two packages.json for better compiling
